import { ThemeDefinition } from './types';

export const THEME_PALETTES: ThemeDefinition[] = [
  {
    id: 'obsidian',
    name: 'Verbum Gold Obsidian',
    category: 'dark',
    bgPreview: '#0c1017',
    surfacePreview: '#151b23',
    accentPreview: '#e5b842',
    textPreview: '#f0f6fc',
    description: 'Paleta canónica de Verbum. Fondo obsidiana profundo con contrastes oro y bronce cálido.',
  },
  {
    id: 'black',
    name: 'OLED Pitch Black',
    category: 'dark',
    bgPreview: '#000000',
    surfacePreview: '#000000',
    accentPreview: '#ffffff',
    textPreview: '#ffffff',
    description: 'Negro puro #000000 absoluto y contraste blanco puro sin tonos cálidos residuales.',
  },
  {
    id: 'tokyonight',
    name: 'Tokyo Night',
    category: 'dark',
    bgPreview: '#1a1b26',
    surfacePreview: '#24283b',
    accentPreview: '#7aa2f7',
    textPreview: '#c0caf5',
    description: 'Paleta oficial Tokyo Night. Azul tormenta, acento azul neón #7aa2f7 y cian, sin tonos amarillos.',
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin Mocha',
    category: 'dark',
    bgPreview: '#1e1e2e',
    surfacePreview: '#181825',
    accentPreview: '#cba6f7',
    textPreview: '#cdd6f4',
    description: 'Paleta oficial Catppuccin Mocha. Tonos terciopelo con acento Mauve #cba6f7 y lavanda.',
  },
  {
    id: 'vercel',
    name: 'Vercel Geist Dark',
    category: 'dark',
    bgPreview: '#000000',
    surfacePreview: '#0a0a0a',
    accentPreview: '#0070f3',
    textPreview: '#ededed',
    description: 'Estética hiper-minimalista de Vercel Geist. Negro grafito y acento azul eléctrico #0070f3.',
  },
  {
    id: 'nord',
    name: 'Nord Arctic Polar',
    category: 'dark',
    bgPreview: '#2e3440',
    surfacePreview: '#242933',
    accentPreview: '#88c0d0',
    textPreview: '#eceff4',
    description: 'Paleta oficial Nord. Azules glaciales árticos y acento hielo #88c0d0 sin amarillos.',
  },
  {
    id: 'sepia',
    name: 'Papiro / Editorial Sepia',
    category: 'light',
    bgPreview: '#fbf6ea',
    surfacePreview: '#f3ecdb',
    accentPreview: '#a76b09',
    textPreview: '#2d241e',
    description: 'Textura cálida de papiro antiguo y papel clásico. Ideal para lectura prolongada sin fatiga.',
  },
  {
    id: 'white',
    name: 'Minimal Pure White',
    category: 'light',
    bgPreview: '#f8fafc',
    surfacePreview: '#ffffff',
    accentPreview: '#2563eb',
    textPreview: '#0f172a',
    description: 'Lienzo blanco inmaculado de alta nitidez editorial, fondos claros y acento azul real #2563eb.',
  },
];
